export const SIMPLE_POPUP_WIDTH = 700
export const SIMPLE_POPUP_HEIGHT = 315
export const DETAILED_POPUP_WIDTH = 800
export const DETAILED_POPUP_HEIGHT = 400
export const CONNECTION_STATE_DIALOG_WIDTH = 500
export const CONNECTION_STATE_DIALOG_HEIGHT = 200