import * as React from 'react'

export class TermsAndConditionsPage extends React.Component<{}, {}> {
    render() {
        return <div className="mostlyText">
            <h1>Terms and conditions</h1>
            
            <p>By using the site <a href="https://maesure.com">https://maesure.com</a>, any other sites that Maesure uses to provide services, Maesure desktop client, or any other clients provided by Maesure (collectively “Services”) provided by Ordered Logic Inc. (“Ordered Logic”, “we”, or “us”), you agree to the following rules that we set out (“Terms”).</p>
<h2 id="Accessing-Maesure"><a href="#Accessing-Maesure" className="headerlink" title="Accessing Maesure"></a>Accessing Maesure</h2><p>Children under age of 13 are not allowed to access the Services or create account. You must also be over the age requred by laws of your country to create an account or otherwise use the Services.</p>
<p>If you are accepting these Terms on behalf of another legal entity, including a business or a government, you represent that you have full legal authority to bind such entity to these terms.</p>
<h2 id="Using-the-Services"><a href="#Using-the-Services" className="headerlink" title="Using the Services"></a>Using the Services</h2><p>We grant you a personal, non-transferable, non-exclusive, revocable, limited license to use and access the Services solely as permitted by these Terms. We reserve all rights not expressly granted to you by these Terms.</p>
<p>Except as permitted in the Services or as otherwise permitted by us in writing, your license does not include the right to:</p>
<ul>
<li>license, sell, transfer, assign, distribute, host, or otherwise commercially exploit the Services; </li>
<li>modify, prepare derivative works of, disassemble, decompile, or reverse engineer any part of the Services; or</li>
<li>access the Services in order to build a similar or competitive website, product, or service.</li>
</ul>
<p>We reserve the right to modify, suspend, or discontinue the Services (in whole or in part) at any time, with or without notice to you. Any future release, update, or other addition to functionality of the Services will be subject to these Terms, which may be updated from time to time. You agree that we will not be liable to you or to any third party for any modification, suspension, or discontinuation of the Services or any part thereof.</p>
<h2 id="Your-account"><a href="#Your-account" className="headerlink" title="Your account"></a>Your account</h2>

<p>To use some features of the Services, you will be requred to create a Maesure account (“Account”), and provide us with an email, possibly a password, and possibly some other information about yourself as described in the <a href="/privacy-policy">Privacy Policy</a>.</p>

<p>You are solely responsible for the information associated with your Account and anything that happens related to your Account. You must maintain the security of your Account and promptly notify us if you discover or suspect that someone has accessed your Account without your permission. We recommend that you use a strong password that is used only with the Services.</p>
<h2 id="Information-you-provide"><a href="#Information-you-provide" className="headerlink" title="Information you provide"></a>Information you provide</h2><p>You retain ownership of any time tracking data that you provide to us while using the Services, and any aggregated data that was derived solely from your time tracking data. We retain the ownership of any data that tracks the usage of the Services, some of which may be submitted by you, as well as any data that was aggregated from the time tracking data across multiple Accounts.</p>
<p>Any ideas, suggestions, and feedback about Maesure or our Services that you provide to us are entirely voluntary, and you agree that we may use such ideas, suggestions, and feedback without compensation or obligation to you.</p>
<h2 id="Limitation-of-liability"><a href="#Limitation-of-liability" className="headerlink" title="Limitation of liability"></a>Limitation of liability</h2><p>IN NO EVENT SHALL ORDERED LOGIC, OR ITS SUPPLIERS, OR THEIR RESPECTIVE OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS BE LIABLE WITH RESPECT TO THE WEBSITE OR THE SERVICES OR THE SUBJECT MATTER OF THIS AGREEMENT UNDER ANY CONTRACT, NEGLIGENCE, TORT, STRICT LIABILITY OR OTHER LEGAL OR EQUITABLE THEORY (I)FOR ANY AMOUNT IN THE AGGREGATE IN EXCESS OF FEES PAID BY YOU, WHICH MAY BE $0; (II) FOR ANY INDIRECT, INCIDENTAL, PUNITIVE, OR CONSEQUENTIAL DAMAGES OF ANY KIND WHATSOEVER; (III) FOR DATA LOSS OR COST OF PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; OR (IV) FOR ANY MATTER BEYOND COMPANY’S REASONABLE CONTROL. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATIONS AND EXCLUSIONS MAY NOT APPLY TO YOU.</p>
<h2 id="Fees-and-payment"><a href="#Fees-and-payment" className="headerlink" title="Fees and payment"></a>Fees and payment</h2>
<p>We reserve the right to require payment of fees for certain Services. If you choose to sign up for any of our Services that carries a fee, you hereby represent and warrant that you are eighteen (18) years of age or older. You shall pay all applicable fees in connection with such Services selected by you. We reserve the right to change the price list and to institute new charges at any time, upon notice to you, which may be sent by email or posted on the Website. Your use of the Services following such notification constitutes your acceptance of any new or increased charges.</p>

<h2 id="Third-party-websites"><a href="#Third-party-websites" className="headerlink" title="Third party websites"></a>Third party websites</h2><p>The Services may contain links to third party websites that are not owned or controlled by us, or the Services may be accessible by logging in through a third party website or service. When you access third party websites, you do so at your own risk. You hereby represent and warrant that you have read and agreed to be bound by all applicable policies of any third party websites or services relating to your use of the Services and that you will act in accordance with those policies, in addition to your obligations under this Agreement. We has no control over, and assumes no responsibility for, the content, accuracy, privacy policies, or practices of or opinions expressed in any third party websites. In addition, we will not and cannot monitor, verify, censor or edit the content of any third party site.</p>
<p>By using the Services, you expressly relieve and hold us harmless from any and all liability arising from your use of any third party website.</p>
<h2 id="Termination"><a href="#Termination" className="headerlink" title="Termination"></a>Termination</h2><p>These Terms shall remain in full force and effect while you use the Services. You may terminate your use of the Services or your membership at any time by following the instructions on the Website. We may terminate your access to the Services or your membership at any time, for any reason, and without warning, which may result in the forfeiture and destruction of all information associated with your membership. </p>
<p>We may also terminate or suspend any and all Services and access to the Website immediately, without prior notice or liability, if you breach any of the terms or conditions of these Terms. </p>
<p>Any fees paid hereunder are non-refundable. Upon termination of your account, your right to use the Services, access the Website, and any Content will immediately cease. All provisions of these Terms which, by their nature, should survive termination, shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, and limitations of liability.</p>
<h2 id="Miscellaneous"><a href="#Miscellaneous" className="headerlink" title="Miscellaneous"></a>Miscellaneous</h2><p>The failure of either party to exercise, in any respect, any right provided for herein shall not be deemed a waiver of any further rights hereunder. </p>
<p>We shall not be liable for any failure to perform its obligations hereunder where such failure results from any cause beyond Company’s reasonable control, including, without limitation, mechanical, electronic or communications failure or degradation (including “line-noise” interference). </p>
<p>If any provision of these Terms is found to be unenforceable or invalid, that provision shall be limited or eliminated to the minimum extent necessary so that these Terms shall otherwise remain in full force and effect and enforceable. </p>
<p>These Terms is not assignable, transferable or sublicensable by you except with Company’s prior written consent. We may transfer, assign or delegate these Terms and our rights and obligations without consent. </p>
<p>These Terms shall be governed by and construed in accordance with the laws of the Province of Ontario.</p>
        </div>
    }
}